services:
  app:
    build:
      dockerfile: Dockerfile
      context: .
    env_file: .env
    depends_on:
      - kafka
  kafka:
    image: apache/kafka:latest
    ports:
      - "${KAFKA_PORT}:${KAFKA_PORT}"
    env_file: .env
    volumes:
      - kafka-data:/var/lib/kafka/data    
volumes:
  kafka-data: